@host = http://localhost:5026
@adminId=2150e333-8fdc-42a3-9474-1a3956d46de8

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free",
    "AdminId": "{{adminId}}"
}

<> 2024-11-28T082723.200.json
<> 2024-11-28T082653.200.json
<> 2024-11-28T082632.200.json
<> 2024-11-27T222918.400.json

###{
#    "Id": "{{adminId}}",
#    "SubscriptionType": "Free",// "Starter", "Pro"
#}

###
